### ISSUE TITLE
Davinci 1.0A Feedback 

### ISSUE THREAD

**Issue by celevra** [luc-github/Repetier-Firmware-4-Davinci#93] opened 2015-07-21 17:43 UTC
Hi,

thank you for your work, you asked for feedback everything worked perfect. 
Installation -> no issues
Calibration -> no issues
first print -> no issues

if there is anything i should test, tell me.
thank you again

regards

celevra

**Comment by luc-github** [comment] 2015-07-21 17:47
Thanks a lot for your feedback, really appreciated
can you confirm you flashed with watchdog enabled ? this is the random issue on 1.0A - first flash make printer to restart, but with latest version I changed WD initialization command

Thanks again

**Comment by celevra** [comment] 2015-07-21 17:58
i'm not sure what you mean with watchdog, i've done exact every step in the step by step Installation guide here on github. 
i've first resettet the printer with the jumper j37, turned the printer on for about 10 seconds.
I'm on OSX and downloaded arduino 1.5.8 Beta
copied the files, changed the configuration to 1 for the A version, changed the port and pressed upload.
i'm not sure if the printer restartet automaticly but there was a really loud "beep"
i have written the settings to eeprom directly on the printer not via repetier host.

hope there is the information you needed, if not guide me in the right direction and i will try to answer ;-)

**Comment by luc-github** [comment] 2015-07-21 18:03
it is perfect if you followed the installation steps it means you did not disabled the WD 
So this is good -yeah I have added the loud beep to show FW is working in case of issue with screen (at the begining screen was randomly scrambled , but it is fixed now and I left the beep)  

Thanks again for your feedback and happy printing :smile:

**Comment by celevra** [comment] 2015-07-21 18:05
sounds great, for clarification, is watchdog a protection mechanism from xyzware or something?

**Comment by luc-github** [comment] 2015-07-21 18:08
it is a safety feature in case of printer loose control for any reason and go into a dead loop without controling heat, if printer is out of control for 8s it will reset and so stop all heaters to avoid damage

**Comment by luc-github** [comment] 2015-07-21 18:08
xyz does not have this feature as far I know

**Comment by celevra** [comment] 2015-07-21 18:09
thanks for clarification
have a good one

**Comment by uladz** [comment] 2015-07-25 19:25
Running 0.92 firmware on Divinci 1.0A for a week already, no issues so far. Noticed two possible problems though:
1. When doing auto calibrating at 2nd point the head seems to be trying to move beyond max Y position. Meaning it moves Y axis all the way to the front and hits hard the closes to the door polley on the right with a loud noise and possible skipping a step. May break the pulley or gears at some point?
2. When printing is finished the head is moving to position x=0, y=0 without changing z position, which is the far right corner of the bed instead of moving to to -33,-12 parking position. I had an issue when once I've cancelled a print when it was still heating up a bed and the bed was at its highest position z=0, the head has moved to x=0,y=0 hitting the bed edge and possibly scratching it.

Otherwise prints are so much better then original XYZ firmware/software, can't compare.
Thanks a lot for all the work!

**Comment by luc-github** [comment] 2015-07-25 19:37
Hi thanks for your feedback
about point 1 : you may need to adjust the Y2 position in EEPROM, currently it is set to : Z_PROBE_Y2 203 and was given by 1.0 owner but 1.0A may be lower, please have a try to decrease it and let me know

about point 2: this is done by your end Gcode of your slicer not by printer itself, you may need to check it, also depending of host you are using there are some predefined macro that may do this behavior and you may need to edit them

Thanks again for the feedback

**Comment by uladz** [comment] 2015-07-25 21:15
Hi Luc,

Thanks a lot for your quick reply, much appreciated. I'll play around with Z_PROBE_Y2 and see if a lower value would work better for 1.0A.

For G-Code I'm using Repetier-Host + Slic3r. Could not find any way to move the hear the far right position yet, it always gets back to 0,0. Slic3r g-code does not have G1 x0, y0 code, so it must be Repetier-Host I think...

Thanks!!!

**Comment by luc-github** [comment] 2015-07-25 21:26
In repetier hosh check this:
![image](https://cloud.githubusercontent.com/assets/8822552/8891299/766052ca-3356-11e5-82d9-fb9c7dc074e9.png)

go to park position should be unchecked or park position should have correct values not 0,0
better unchecked as if you kill a job at 50% go to Z=0 is very bad idea as model may hit carriage rods

**Comment by uladz** [comment] 2015-07-26 00:50
Thanks a lot, will try it out now!

**Comment by uladz** [comment] 2015-07-27 17:03
BTW, y=203 for the probe seem to be correct value, it stops right before the pulley. For some reason when you do auto calibration the head smashes into pulley though... Wait a minute, in the EEPROM settings I see that probe Y position is set to 205 instead of 203! That's the problem. Also max X length should be 237 and mx Y length = 215. These values seems to work fine.

On the repetier config, setting X=-33, and Y=-12 resolves the issue with the head going into position 0 upon job completion or job cancel. I've put Zmin to like 10, so the head is always above the bed. Repetier would only lower the bed if its Z position is < Zmin, but would never rise it, so no problem with hitting hit carriage rods.

**Comment by uladz** [comment] 2015-07-27 18:34
Gee, I need to be careful, twice hit a bed with a print head while moving it around to get correct max coordinates. Unfortunately there is no "blocking" protection in the motors, they continue to pull all the way even if a head is not moving any more and belts are skipping. Fortunately belt tensioners are saving mechanisms from fatal failure. Well...

**Comment by luc-github** [comment] 2015-07-27 19:00
Ok so you mean what should be changed for 1.0A :
```
#define Z_PROBE_Y2 203
#define Z_PROBE_Y3 203
```
and 

```#define Y_MAX_LENGTH 215 - ENDSTOP_Y_BACK_ON_HOME```

as X is already correct : ```#define X_MAX_LENGTH 237 - ENDSTOP_X_BACK_ON_HOME```

**Comment by uladz** [comment] 2015-07-27 19:03
yep. but i thing 1.0 and 1.0A mechanically are the same, only the board is different + minor cosmetic changes. so this might be true for 1.0 too.

**Comment by uladz** [comment] 2015-07-27 19:04
btw, off topic question, do you know if XYZ sells spare parts? looks like I've cracked one of the bearing holders :(. can not find any spares on XYZ website, only replacement bed, head, and tool.

**Comment by luc-github** [comment] 2015-07-27 19:14
1.0 values come from 1.0 owner, so I won't change them I think -  I will apply them only on 1.0A

about spare parts check voltivo forum, some people did some metal bearing holder, you may ask them, or there are printed version available on thingiverse also

**Comment by uladz** [comment] 2015-07-27 19:21
super thanks!

**Comment by celevra** [comment] 2015-07-27 19:38
recognized that behavior also, to park the extruder i use the gcode M100
works if its not allready parked, if it is parked you will hear the loud noise.
where do i have to change these values, i think in arduino IDE and flashing again, am i right?

**Comment by luc-github** [comment] 2015-07-27 19:45
all these values are in EEPROM no need to flash

and to park (XY) the command is G28 XY
This home XY but not Z

**Comment by luc-github** [comment] 2015-07-27 20:15
update done https://github.com/luc-github/Repetier-Firmware-0.92/commit/29d84876b834f990eae1b4474ea615e332a216b3
Thanks for your feedback

**Comment by uladz** [comment] 2015-07-27 20:27
BTW, doing auto leveling - does it actually affect anything? If I store the values in EEPROM I do not thing Repetier takes them into account anyway.

**Comment by luc-github** [comment] 2015-07-27 20:37
need to be sure autolevel is set to 1
when doing autolevel it generate a positions matrix used by FW, it is tranparent for host as FW will adjust the z position according the positions matrix when printing.
When using autolevel you will see z moving up and down permanently during printing

That said - I never use autolevel, only to validate code, I only use manual level, once done properly, I do not need to redo for several prints and when you get used to it, IMHO it is really faster than autolevel.

**Comment by uladz** [comment] 2015-07-27 21:32
Aha... I see. BTW, the Z_PROBE_HEIGHT is wrong for 1.0A, it's set to .28 now but I think the correct value is around .54. I'm comparing autolevel vs manual with paper, will let you know once I know the correct value (if I do not brake my printer before :)). Also one question, if I do manual leveling with paper, what's the Z-offset in slicer to use? Keep 0?

**Comment by luc-github** [comment] 2015-07-27 21:34
yes 0

**Comment by uladz** [comment] 2015-07-27 22:50
Okay, Z_PROBE_HEIGHT=0.56 seems to give me the most closest to paper-leveling numbers. I'll keep an eye on the level over time to make sure the this is the right value for 1.0A.

**Comment by thevisad** [comment] 2015-07-28 00:09
I just pulled out my feeler gauges, dropped the hot end to the plate and measured .38mm between the bed and the end of the Z probe  .56 is too much and .28 is too little.

**Comment by uladz** [comment] 2015-07-28 00:11
how did you measure?

**Comment by thevisad** [comment] 2015-07-28 00:13
I pulled out my feeler gauges, https://en.wikipedia.org/wiki/Feeler_gauge

**Comment by uladz** [comment] 2015-07-28 00:25
I see. You need to take into account the metal brackets that are in all 4 corners of the bed and that are used as contacts when auto level is measuring distance in 4 corners. This will and approx. 0.2mm and bring your number right to mine :).

I did manual calibration with paper sheet, then I have run through auto calibration and pulled the measurements right from XYZ Davinci itself.

Agree?

**Comment by thevisad** [comment] 2015-07-28 00:34
The metal brackets in the corner are .58mm high, found by dropping the Z probe to the metal bracket until it makes contact. Then with the tip of the hot end over the bed itself, using the feeler gauge to identify the distance between the hotend and the bed. The setting indicates that this is the distance between the very tip of the hot end and the very tip of the z probe. This follows the same setting in Marlin and should not be offset by the height of the metal brackets. 

/** The height is the difference between activated probe position and nozzle height. */

**Comment by uladz** [comment] 2015-07-28 00:36
.58 sounds good

**Comment by thevisad** [comment] 2015-07-28 00:39
I corrected the above actually, I forgot to add the two numbers together to get the actual thickness of the bracket. I verified this by pulling out the caliper and throwing it on the bracket. So the offset value does not include the bracket thickness.

**Comment by uladz** [comment] 2015-07-28 00:56
You've lost me here a little bit. Shouldn't this be way around, 0.92 is the metal bracket, 0.38 is the diff between probe and tip. Then the probe height would be 0.92-0.38=0.54 in your case as this will be the distance between tip and bed when probe touches the metal bracket. Or I do not understand something...

**Comment by thevisad** [comment] 2015-07-28 01:04
Yup, you are right, I am a bit tired and was adding the two. I at least have the correct offset for mine now. I would best it's pretty close for everyone elses (give and take a little due to the bracket bending).

**Comment by uladz** [comment] 2015-07-28 03:17
@thevisad, we are in agreement, awesome! :+1: 
@luc-github, I guess you can update the Z_PROBE_HEIGHT too for 1.0A.

**Comment by uladz** [comment] 2015-07-28 03:47
@luc-github, is it possible to add a menu item for lowering bed to the bottom? Would be extremely useful for prepping bed for a new print.

**Comment by luc-github** [comment] 2015-07-28 05:38
0.28 is value provided originaly by BGM and never checked it - when going home I will see if this value works for my 2.0

About menu - I use Z position there is a 100mm set, but can imagine a menu item to position to max Z

**Comment by luc-github** [comment] 2015-07-28 06:17
I have created 2 trackers https://github.com/luc-github/Repetier-Firmware-0.92/issues/98 and https://github.com/luc-github/Repetier-Firmware-0.92/issues/99 - will process them later - thank you

**Comment by klHaribo** [comment] 2015-09-02 16:20
the new firmware works perfect.
Changed to german language, but only some lines seems to be translated. 
I'll try to find some time to work on it.
Had some issues with heater decoupled, but it seems this is caused by opening the door and cold air flows into the printer.
Upload to SD_Card via Host would be great ;)

**Comment by luc-github** [comment] 2015-09-02 23:50
Hi thanks a lot for your feedback
Yes sorry - I only maintain English (too lazy to do others languages, even French and Spanish....) all menu need to be reviewed in others languages as they are for 20x04 screen when Davinci's screen is 16x04 one

For heater decoupled you may adjust the setting for your printer - it may be too sensitive 
```
// If the temp. is on hold target, it may not sway more then this degrees celsius, or we mark
// sensor as defect.
#define DECOUPLING_TEST_MAX_HOLD_VARIANCE 15
// Minimum temp. rise we expect after the set duration of full heating is over.
// Always keep a good safety margin to get no false positives. If your period is e.g. 10 seconds
// because at startup you already need 7 seconds until heater starts to rise temp. for sensor
// then you have 3 seconds of increased heating to reach 1°„C.
#define DECOUPLING_TEST_MIN_TEMP_RISE 1
```
and

```
/** Time in ms between a heater action and test of success. Must be more then time between turning heater on and first temp. rise! */
#define EXT0_DECOUPLE_TEST_PERIOD 30000
```

the upload to SDCard from host already exists and works, but it uses repetier protocol which is very slow compare to wifi SDCard transfert

**Comment by klHaribo** [comment] 2015-09-03 08:45
due to my poor school english I don't really understand this text ;)
I found these settings already. changed DECOUPLING_TEST_MIN_TEMP_RISE to 3, autotuned PID's and it seems to work for now.
Printer only stopped when I was doing something in another room, seems like he wanted to fool me ;)

**Comment by luc-github** [comment] 2015-09-03 08:54
Hmm ```DECOUPLING_TEST_MIN_TEMP_RISE  3``` will increase risk of decouple error for my understanding, the best is to increase extruder instead
```EXT0_DECOUPLE_TEST_PERIOD 60000```
also check your connectors they also can be the root cause in some position

**Comment by The-Experimentalist** [comment] 2015-10-15 07:44
One note is that the display on the printer for the 'Light AutoOff' prompts for a value in ms but is actually really minutes. By comparing the values set on the printer and those stored in the EEPROM I can see that the value is configured on the printer in minutes and stored on the EEPROM in ms

Not a big issue but thought I would mention it for any later revisions. Thanks again.

**Comment by bagwan** [comment] 2015-10-19 10:58
Hi!
I have flashed repetier on my 1.0A before a Week, and printed some Meters of Filament without any Problem. Yesterday I would start a Print, and it stopped after 2 minutes with "Heater Decoupled" Okay, checked the Heater and the Cabels. No defects. So I startet a Job and measured the Pinoutput on the Board for the Heater. There are no Power on the Pins. 
Do you think I have a Problem with the Firmware/Software?, or is it a real Defect on the Board? In a Forum, which I´ve asked for a circuit Diagramm, theres another Person, which have exact the Same Problem. Flashed with Repetier, printed a few Meters, Then "Heater Decoupled"
Thanks for your Help

**Comment by luc-github** [comment] 2015-10-19 11:15
Can have several factor for decoupled error:
1- the connectors (sensor/heater are loose) this is common problem on Davinci - several people changed their connector or soldered cable directly and ensure cable are not moving
2- the door is open or a fan is blowing on extruder and so do perturbation on air flow and heating
3- hardware issue - no heat

none is FW/SW
 
first you need to eliminate point 2 by disabling additional fan if any and close door
if not point 2 to debug problem you can flash FW disabling decouple test in configuration.h then heat
if heating it is not point 3 but point 1 - check also all 3 led are working on main board if one of them is off it you got a hardware problem

you also can observe the heating chart in repetier to monitor temperature changes according extruder position to see if there is no short

Hope it help

**Comment by bagwan** [comment] 2015-10-19 11:37
First, thanks for your Quick reply.

The Cable and the Heater is definitv ok. The 3 LEDs on the Board are working. When the Heater should heat up, then should the Connector on the Board have 12V. But my Multimeters shows no Volts. on the Pins. So i Think, there is defective on the Board.
Is it meanwhile possible to go back to XYZ Firmware? Because i have actually 4 Weeks Rest Guarantee...

**Comment by luc-github** [comment] 2015-10-19 12:14
No for 1.0A there is no way to revert , XYZ have implemented a lock for this and no tools is able to flash back but the one from support 
 I suggest you to fix the problem here a thread for the problem:
http://voltivo.com/forum/davinci-peersupport/734-1-0a-no-power-to-extruder-heater-fix

or use the jumper to erase FW and contact XYZ and tell them you power on your printer and there is 2 black bar and never mention repetier FW they will send you a new board or ask to send printer back for fixing

**Comment by bagwan** [comment] 2015-10-19 18:07
Thanks 1000Times. That was my Problem. Fixed the Heater Problem.
Made my Day

**Comment by thomastech** [comment] 2015-11-04 19:29
Flashed my 1.0A (3F10A hardware version) from XYZ V1.0.3 to Repetier 0.92 a couple days ago. First, a big Thank You to the developers / contributors.

Some comments / feedback:

1. I used Arduino 1.6.5. Because of my confusion on the directory location of the two AdditionalArduinoFiles I fought the 2-black bar (brick) issue for awhile. After getting the files into the correct directories (under /users) things went much better. None of this would have occurred if I had used Arduino 1.5.8 since the two files go in more obvious directories ( under /programs files).

2. On my 1.0A the top cover open Alert did not work. I changed the TOP_SENSOR_PIN from 6 to 64 and that solved the problem for me.

3. I experienced a lot of host "wait" command delays during long prints. Increasing Simplify3D's buffer cache size to 2024 has reduced these events, but the wait delays still randomly occur. I understand that the issue is related to the TIMER1_COMPA_VECTOR() interrupt. If there is a patched version of HALL.cpp then I would definitely like to try it out.

Overall I really like the 0.92 upgrade versus the stock XYZ firmware. The stock feature I really miss is the ability to do standalone USB prints (send file, then shut off PC). So now I am looking into octoprint as a workaround. 

- Thomas

**Comment by The-Experimentalist** [comment] 2015-11-04 20:05
Not tried it yet but I believe you can do USB prints with Repetier Host but it is slow transfer due to using Repetier protocol to transfer the files from what I remember reading, I am sure Luc cac confirm or deny this ability. For simple cheap file transfer I just have a micro SD card extension to bring the SD into the main chamber. I have a DaVinci AIO and mounted mine on the redundant scanner module. I just pop out the SD and transfer the files using a Micro SD USB adapter on the PC and then put it back in. It only takes a couple of minutes and is cheap, see pictures. One other mod I made was to break out the firmware erase jumper to a button which I mounted on some prototype PCB and printed a little holder for. I can also access this from the main chamber so no need to take the back off again, came in handy when I was first messing around and will make any future firmware updates a 2 minute job.

**Comment by thomastech** [comment] 2015-11-04 20:57
// Not tried it yet but I believe you can do USB prints with Repetier Host 
// but it is slow transfer due to using Repetier protocol to transfer the files 
// from what I remember reading.

I have a Prusa i3 with Marlin firmware that can do this, but it is much too slow. So SD card printing is the workaround. But the Prusa printer is not my main go-to machine, partially because of this inconvenience.

// For simple cheap file transfer I just have a micro SD card extension 
// to bring the SD into the main chamber.

Same here, long ago I also moved the SD card socket to a better place (the front of the printer). 

![sd_card1_1200](https://cloud.githubusercontent.com/assets/10354989/10951194/ec5f10c6-82f0-11e5-9a8a-3de759a42299.jpg)

But my davinci printer is in a remote room on the first floor (so I don't have to smell ABS and hear the noise). My office is on the second floor, so running back and forth was inconvenient. So my final solution was to plug the stock davinci into a wireless USB printer hub. This allowed me to send a print file to the davinci printer (host PC not needed after the file xfr). For my situation, this has been a fantastic way to print. So I miss being able to do print file xfr's after the 0.92 upgrade.

![usb_2_1200](https://cloud.githubusercontent.com/assets/10354989/10951280/76d4d132-82f1-11e5-9ca6-55903291bd9e.jpg)

Maybe Luc can advise on good way to achieve what I need. But I have a feeling the raspberryPi octoprint solution is going to be needed.

// One other mod I made was to break out the firmware erase jumper to a button
// which I mounted on some prototype PCB and printed a little holder for.

Ditto. I added a pushbutton reset switch during my frustrating attempts to get Arduino 1.6.5 to build working firmware. Much better than shorting the PCB's pads with tweezers. 

- Thomas

**Comment by The-Experimentalist** [comment] 2015-11-04 21:18
If you go the Octoprint route you may want to read the article by Jake also recommended by Luc:

http://voltivo.com/forum/davinci-peersupport/501-da-vinci-setup-guide-from-installation-to-wireless-printing

There is a section on "Using OctoPrint for Wireless Printing" and he recommends the BeagleBone Black over the Raspberry Pi.

Might be worth a read?

**Comment by thomastech** [comment] 2015-11-04 22:29
@The-Experimentalist: Thanks for the OctoPrint link. Too bad the RPI is not recommended since I already have a RPI2 model B and a RPI model A+. But it seems that I will need to buy a BeagleBone if I build the OctoPrint project.

In the meantime, fingers are crossed that there's a magic 0.92 upgrade that has buffered USB printing. :)

- Thomas

**Comment by The-Experimentalist** [comment] 2015-11-04 22:32
Keep reading. I think if you already have a RPI then you can use it. Jake is recommending BBB if you don't already have hardware I believe. I think if you search you will find info on how to use your RPI. Good luck.

**Comment by luc-github** [comment] 2015-11-04 23:41
@thomastech thanks for sharing I will add the new pin for top sensor, about the patch - repetier is still working on it and I am waiting an official release as I do not use USB at all I prefer to be sure it has been heavily tested -  it seems more than a simple patch as I was suggested initially that is why repetier is testing it, this is my trigger to do a new sync between official repetier and davinci one.
About 

To print from SDCard, I recommend Wifi SDCard (toshiba one) copy is really fast
then as you already make your Davinci wireless, launch remotely the SDCard print using repetier host

or you can add an ESP module and my FW https://github.com/luc-github/ESP8266
so you can use repetier host to launch remotely the SDCard print or use the web interface to launch it but you still need a wifi SDCard for faster file transfer

**Comment by luc-github** [comment] 2015-11-04 23:45
@The-Experimentalist / @thomastech  Octoprint is good solution if you want all in one (slicer +host) and follow by webcam, it works on all Raspberry so no worry - but it use USB, and in my opinion SDCard print is more reliable - I used for a while on Pi and worked well

**Comment by thomastech** [comment] 2015-11-05 00:59
@all: I'll have to think about how to settle my quest for recreating / emulating the standalone USB printing method I've grown to enjoy using. My USB print buffer hub worked brilliantly for me on the stock davinci firmware (100% reliability), so it is unfortunate it is not a viable approach for buffered printing on my 0.92 upgraded printer.

At the moment I think I will back off from OctoPrint. Now I'm leaning towards ordering the Toshiba 8GB WiFi SD card.

@luc: In regards to the upcoming patch for fixing the host-command wait delays, if you need someone to test your patched davinci version then just holler.

New Question: On my Prusa i3 Marlin printer I added some custom hardware/software features. I'd also like to do some customization on my Repetier daVinci. There are several unpopulated connectors on the 1.0A (3F10A) board. I have the fantastic pins list that Luc posted -- Is there by chance a published list that shows which CPU pins are found on the various unpopulated PCB connector pads? 

- Thomas

**Comment by luc-github** [comment] 2015-11-05 01:05
sure, will do a test branch for this, will do annoucement when ready, thanks

I am not aware of this document, as so many boards now ....

**Comment by thomastech** [comment] 2015-11-07 03:03
I've run into an odd problem with the extruder heater. On the first print everything works great. But on the next print the extruder heater stays off. {note: The bed heater operates as expected.} The printer ends up in a hang because it's waiting for the extruder to heat up. I can see "wait" messages in the communication window.

My workaround is to reboot each time I print. It also works if I stop the print (using Simplify3D's STOP), disable both heaters, then send the job again. 

I am printing by USB. I need to test it with a SD card to see if the problem occurs there too. But I have a hunch that SD card printing does not do this (otherwise there would be reports about it).

- Thomas

**Comment by luc-github** [comment] 2015-11-07 07:57
looks like you have something wrong in your end code, can be a wrong command like waiting temperature is 0, which will never happen unless you live in arctic place, or some typo issue that freezs the printer

**Comment by thomastech** [comment] 2015-11-07 18:05
The problem does not occur if I print from the SD card. 

I discovered that if exit Simplyfy3D at the end of the print, then restart it, the problem does not occur. So at this point I believe that Simplify3D's and/or USB printing is the culprit. 

BTW, I see endless "wait" messages in the host interface when the problem occurs and the Command Buffer value is 0 (empty que). These symptoms suggest it could be the HALL.cpp interrupt bug. When I have some extra free time I'll install the Repitier Host to see how it behaves. If it does it too then that would suggests it's related to the HALL.cpp issue. 

For the sake of full disclosure, this is my starting script:
```
M300 S500 P500; Beep
M104 S0 T0; turn off extruder
M140 S0 ; turn off Bed
G90 ; Absolute
G28 X0 Y0 ; home
G1 Z200 ; Lower bed
M100 ;Cleaning
M84 ; Disable motors
M107 ; Fan Off
M117 Printer Ready 
M300 S500 P500; Beep
M300 S1000 P500; Beep
M300 S1500 P4000; Beep
```
_Note: My tiered bed/extruder temperature commands are used because the bed takes longer to heat than the extruder (and I don't like the extruder to cook while the bed warms up). But I have used traditional heating commands and the problem still occurs._

Below is my ending script.
```
M300 S500 P500; Beep
M104 S0 T0; turn off extruder
M140 S0 ; turn off Bed
G90 ; Absolute
G28 X0 Y0 ; home
G1 Z200 ; Lower bed
M100 ;Cleaning
M84 ; Disable motors
M107 ; Fan Off
M117 Printer Ready 
M300 S500 P500; Beep
M300 S1000 P500; Beep
M300 S1500 P4000; Beep
```
- Thomas

**Comment by thomastech** [comment] 2015-11-07 19:37
I found it! For some reason the printer stops echo'ing the M105 temperature data at the end of a print. 

Simplify3D sends the M105 command when the USB connection is established, but not with each print. So I added M105 at the bottom of my ending script and also at the top of the starting script.

I'm not sure if this is a "bug" or expected behavior. Fortunately the M105 script fix is easy.

- Thomas

**Comment by luc-github** [comment] 2015-11-08 00:12
looks more a communication issue if this not happenning on SD card printing
what is your baudrate on printer and simplify? what cache size do you use? what version of simplify?

**Comment by thomastech** [comment] 2015-11-08 02:32
Baud 230400. Buffer cache 2024. Simplify V3.0.2.

Prints come out fine. Only issue has been that temperature data is disabled at the end of a print. I can reliable repeat this.

**Comment by luc-github** [comment] 2015-11-08 03:30
you may give a try to 115200

**Comment by thomastech** [comment] 2015-11-08 19:25
A bit of detour, with a happy ending...

I have an extension cable on my daVinci's SD card reader. Because the Card Detect Switch is on the motherboard's SD socket, using the extension cable adversely affects the SD Card Detect feature. This causes problems during card swaps. This isn't an issue for WiFi card users (but affects manual card swappers like me).

So yesterday I decided to add a card mount function to the Repetier SD Card menu. But after reviewing the code I saw that all the work was already done. All I had to do was change the SDCARDDETECT value to -1. Now the SD Card menu has "mount" and "unmount" functions. Although not ideal, these are the workarounds to the missing Card Detect signal.

So back to the extrusion heater problem. After reflashing with the SD Card patch, the heating issue was cured! This made no sense, so I reflashed with my original firmware. It too no longer had the problem. All my menu settings are exactly the same, so I have no idea how this solved the problem.

> you may give a try to 115200

Not that it really matters now, but the ArduinoDUE's Native USB port does not observe the baud setting. It negotiates the fastest possible speed and ignores any user host settings applied to the com port. You can see this for yourself by changing the baud and uploading a file. The upload times will be the same. On the otherhand, the DUE's Programming port utilizes a baud setting (because it is a hardware serial port with USB interface chip).

Speaking of USB speed, I did a file upload benchmark. I tested a file that would normally take under a minute to load to the stock daVinci. With Repetier, it takes 6 minutes. Too bad the gcode data was not compressed since such a trick could decimate the data for much faster loads (perhaps as fast as a stock daVinci).

Thanks for all the handholding / advice during my transition to Repetier. I think I've got my upgraded printer all dialed in, prints are looking good. So hopefully I won't bother anyone here for awhile. :)

- Thomas

**Comment by Vaporizin** [comment] 2015-11-09 14:58
@luc-github Hi, thanks for all of your guides and help! All of your information has been great and got me out of some tricky situations.
Im running the Davinci 1.0A installed perfectly as per your steps, flashed fine and calibrated and printed wonderfully after some adjusting of the Slic3r settings.

The only problem I have come in to so far is the USB issue, stopping mid print. However I transferred to using SD and all seems to be working well and fully printing. 
When tracking from the comp it seems to lose connection with the printer around 52% mark (SD card continues to print) and while the usb is still recognized in device manager as COM6 it isnt picked up by the printer, additionally if my pc locks the mouse and keyboard stops working and I have to unplug and plug back in.

So obviously this is an issue with Windows, USB side of things but im not too sure where to start. 
I have copied all the files correctly, and replaced (Hardware folder etc), reinstalled Arduino drivers.
Any help would be appreciated!

**Comment by luc-github** [comment] 2015-11-09 15:04
@Vaporizin please have a look here https://github.com/luc-github/Repetier-Firmware-0.92/issues/38

**Comment by luc-github** [comment] 2015-11-10 14:49
Hi anyone else got issue with TOP sensor with 1.0A ? just to confirm pin 6 is incorrect for all 1.0A and pin 64 should be used on all 1.0A like for AiO

thanks

**Comment by trickykidd** [comment] 2016-01-25 03:30
hi, seem to have an issue printing higher than about 100mm, i assume this is due to z axis calibration.. anyone had this problem or have a quick solution? thx

**Comment by luc-github** [comment] 2016-01-25 03:46
> seem to have an issue printing higher than about 100mm(extruder drags print off of bed)

Can you elaborate ? you mean extruder is too high compare to bed ?
Yes can be Z calibration also can be model issue

**Comment by trickykidd** [comment] 2016-01-25 03:49
quick reply :)! i am fairly new to all this, only just flashed the printer on friday. the print is ok up to a height of roughly 100mm, though the quality still needs improving, at about that height the bed height seems to be off by so much the print gets dragged off the bed, ie. the extruder knocks into the print or is so close it drags it. just looking into setting the amount of steps/mm on the z axis for 1.0A.

**Comment by luc-github** [comment] 2016-01-25 03:55
be also sure acceleration  / speed on z axis is not too fast that printer cannot handle it, so the result finally bed do not move as value is too high

so yes first thing check your Z calibration, it is fast

**Comment by Aikon2000** [comment] 2016-03-23 01:40
Hi All,
I hope someone can help with explaining a few things... Most probably luc-github...

I'm  running Repetier on da Vinci 1.0A. Using self levelling is a bit off, but it could be perfect if I could adjust a few things in the code.
 Front of the bed is about 0.2mm too low after self levelling (always).

 1. How and where in the code can I set this offset so that whenever auto levelling is initiated it would be included? 
 2. When auto levelling is in progress it always drops the bed 10mm for each movement, 5mm would be more then enough.
 Where can I change that? - timesaver

 Thank You!

**Comment by luc-github** [comment] 2016-03-23 21:52
Autoleveling is known to be buggy - at least until 0.92.8, please check http://www.repetier.com/documentation/repetier-firmware/z-probing/, current FW is based on 0.92.3 and I did not finished to integrated 0.92.6 and 0.92.8 changes yet - got very few free time these last 3 months
I hope to do it soon

**Comment by Aikon2000** [comment] 2016-03-30 00:34
Hi Luc, I had a look at the link you provided, but couldn't find if there even is a way to set up different Z heights for points it measures... Although I did notice the  BED_LEVELING_METHOD 0 with 3 probe points, P1 and P2 are the other way around with DaVinci, I know it measures P2, P1, P3, but does it take it into account like that as well?

**Comment by luc-github** [comment] 2016-03-30 19:50
BED_LEVELING_METHOD is in 0.92.8 not yet in DAVINCI which is based on 0.92.3

**Comment by opensourcefan** [comment] 2016-06-30 20:09
My used but new to me 1.0A was soft bricked when I got it so I'm not sure if this counts as feedback for 1.0A but 0.92 is working excellent. I installed whichever version is on the main code page and don't think that it's 0.92.10 It took a lot to bring this printer back to life so I'm hesitant on flashing again right now but will do so soon I'm sure. Thank you so much for this quality firmware, it truly has made this printer quite powerful.

**Comment by luc-github** [comment] 2016-06-30 20:16
thanks for your feedback - master is actually 0.92.3 
will merge the development branch soon but still doing some tests on 0.92.10

**Comment by HorstBaerbel** [comment] 2016-07-20 12:37
I have tried out the 0.92.10 alpha on the Da Vinci 1.0a and it worked very well for me. I had trouble with the auto calibration feature though, but probably that's just me, so I calibrated with the manual "paper" method with the printer turned off, which worked fine.

**Comment by luc-github** [comment] 2016-07-20 13:49
Hi thanks for sharing, that is true the languge menu end when you press left , same menu is in settings

what trouble did you get witbauto level? to be honest I only use manual calibration with sheet of paper, take me one minute per month 😄

**Comment by HorstBaerbel** [comment] 2016-07-20 18:31
Ah, Ok. I think I remember pressing all of the buttons but couldn't leave the menu in any way, so I power-cycled the printer... ;) Afterwards the printer language was english, which is fine with me anyway.
The auto leveling always reported "failed", supposedly because the bed was too low, so I tried manual leveling with a sheet of paper with the printer turned off. I have also tried the manual leveling feature in the firmware, which worked quite well. Good feature!

**Comment by luc-github** [comment] 2016-07-20 18:37
yes auto leveling is actually very sensitive as it is to fine tune a bed already close to level, also need to have the plate and probe very clean to do contact and that not always the case.
Me I use the feature without saving to check if all 3 values are close after a manual leveling - that is why I display values :smile:

**Comment by alexbaucom17** [comment] 2016-08-23 13:57
Unless I am mistaken the latest da Vinci firmware (2.1.2) has blocked the ability to flash the printer using pin J37. I have tried several times and instead of getting black bars I just get the word initializing. Then when the printer is power cycled again it boots back up into the normal firmware like nothing happened. I saw a report of the jumper still working on 2.1.1 so I think maybe they changed something in the firmware.

**Comment by luc-github** [comment] 2016-08-23 14:17
Jumper wipe flash at Hw level, nothing left from fw point of view, even bootloader is removed
i do not thing anything can be done in fw to block wipe flash using jumper

**Comment by alexbaucom17** [comment] 2016-08-23 14:20
Hmm... Okay maybe I am somehow doing it wrong then. I will keep trying!

**Comment by alexbaucom17** [comment] 2016-08-23 14:31
Okay. I was indeed doing it wrong! I think the pin I was using to try to bridge the first time wasn't conductive enough or something. I grabbed some tweezers and it worked great. Just got the new fw flashed and I'm excited to try it out!

**Comment by luc-github** [comment] 2016-08-23 15:51
good, enjoy

**Comment by Vaporizin** [comment] 2016-09-14 07:47
Hi @luc-github ,

After 6+ months, printer started to have some feed issues. Probably hardware related. Heater Decoupled issue showed up. 
Contacted XYZ after checking extruder pins on mobo and receiving 0V across them when trying to heat extruder. 
They advised the board was faulty and sent me a replacement (refurbished I think).
Re-flashed repetier etc, went to load filament and all was fine heated up okay. 
Pressed yes to load a second time to push more through to see if feed was okay and printer just turned off. Didnt come back on. Flicked off/on switch and restarted fine. However back to heater decoupled issue. 
From research it seems that the J4 fuse on mobo is blowing for some reason, could be wire short or something?
Any advice or help to get to the bottom of this would be appreciated!

**Comment by luc-github** [comment] 2016-09-14 09:33
hi decouple error can have many root cause, from loose connector, to broken wire and even fuse blow

to debug it you can disable decouple test in configuration.h

so you will see if your extruder heat or not

**Comment by Vaporizin** [comment] 2016-09-14 09:58
Definitely have ruled out loose connectors, couldn't measure voltage off the extruder pins on motherboard.
I just took out the replacement board and put my old one in, soldering the J4 fuse. 
Extruder heats up fine. Just need to throw a 3A in line fuse on the cable and it should fix it short term. 
Need to work out the underlying cause, Im thinking a short in wiring from thermistor/extruder is only thing I can think of.

If I disable decouple test does that just stop the error from showing?

**Comment by luc-github** [comment] 2016-09-14 10:04
yes disable decouple test will not check any temperature issues and not
stop anything anymore

**Comment by DaAwesomeP** [comment] 2016-09-22 02:21
I currently have an issue where after manually or automatically (or even both) leveling the bed, the head starts way to high up or too low from the bed. This is probably a setting in Repetier-Host, but I don't know what is causing this.

**Comment by luc-github** [comment] 2016-09-22 02:30
you mean Z position is not good when you start to print ?
Check EEPROM zmin/Zhome is 0 and also in your slicer/host there is not z offset

**Comment by zipippino** [comment] 2017-08-28 15:04
Hi, i have a DaVinci 1.0A
I have succesfully installed the repetier firmware but while printing here the error comes. The extruder is too much close to the bed and so the extruder crushes on the printed plastic and makes a disaster. That's because the bed is too much elevated, i think. How could i solve?

![settings1](http://i.imgur.com/tS6FSwO.png)
![settings2](http://i.imgur.com/fsqgGh4.png)
![settings3](http://i.imgur.com/mLbCrzR.png)

**Comment by fang64** [comment] 2017-10-29 19:55
@DaAwesomeP I actually am noticing that when the heated bed/nozzle are active the bed seems to move up and down very small amounts with the fan speed of the power supply. I am suspicious that the power supply is failing, however I have another Da Vinci still running the factory firmware and it doesn't exhibit this behavior so not entirely sure what's causing it unless the da vinci firmware doesn't run the nozzle and bed as aggressively. I'm going to swap power supplies to see if it stops. However initially I thought it was the firmware causing the issue. not entirely sure at this point though.

**Comment by DaAwesomeP** [comment] 2017-10-31 08:20
@fang64 Unfortunately, I no longer have access to this printer. I never noticed the bed moving like you describe, but I don't think that I would have noticed that unless I was staring at the threaded rods.

**Comment by MRNASTYLLC** [comment] 2018-01-13 01:13
I’m new here and looking for help on xyz printer that’s been flashed.   Where do I start to make such a post?   
Thanks

**Comment by luc-github** [comment] 2018-06-02 19:49
Close as now outdated

**Closed by luc-github** 2018-06-02 19:49 UTC
Labels: Feedback Needed
